USE PROJETO;

/* ENTRANDO COM MAIS TELEFONES */

UPDATE CLIENTE SET TELEFONE = '97865434' WHERE NOME = 'Joao';

SELECT * FROM CLIENTE;

UPDATE CLIENTE SET TELEFONE = '229223110 - 97865434' WHERE NOME = 'Joao';

SELECT * FROM CLIENTE;

SELECT ENDERECO, COUNT(*) FROM CLIENTE GROUP BY ENDERECO; /* MOSTRANDO UMA MODELAGEM ERRADA, ESSE TIPO DE MODELAGEM 
EU TRAGO UMA INFORMACAO SEM SABER ESPECIFICAMENTE O QUE PLANEJO VIZUALISAR DEIXANDO CONFUSA A INFORMACAO ABORDADA */

