USE PROJETO;

/* POR EXEMPLO, ARMAZENAMOS NO BANCO A VENDA DE JNAIERO, FEVEREIRO E MARCO O TOTAL DAS VENDAS E O 
IMPOSTO PAGO AO GOVERNO. FAZEMOS ISSO DURANTE MUITO TEMPO. DE UMA HORA PRA OUTRA O GOVERNO MUDA 
A ALIQUOTA DO IMPOSTO. COMO FARA SENTIDO OS PAGAMENTOS ARMAZENADOS ANTERIORMENTE? AQUI NOTA-SE 
QUE ARMAZENAMOS DADOS E ARMAZENAMOS INFORMACOES CORRESPONDENTES AOS PROCEDIMENTOS EXERNOS. 
DEVEMOS APENAS ARMAZENAR OS DADOS, POIS ELES SAO SUFICIENTES PARA GERAR A INFORMACAO.

MODELAR SER UMA ARTE, ALGO QUE SE APRENDE COM A PRATICA. E VOCES PODEM SE PERGUNTAR: 
MAS SE SER ALGO QUE SE APRENDE COM A PRATICA, COMO QUEM ESTA COMECANDO, APRENDE?

ASSIM COMO PETER CHEN CRIOU O MODELO DE ENTIDADE E RELACIONAMENTO, O MSER, FORAM CRIADAS 
FORMAS NORMAIS, QUE SAO DIRETRIZES PARA APLICAR EM MODELAGEM DE AMBIENTES OLTP OU 
AMBIENTES TRANSACIONAIS DE BRANCOS DE DADOS.

HOJE TEMOS MAIS DO QUE 3 FORMAS NORMAIS, MAS AO NORMALIZARMOS UM BANCO ATE A SUA TERCEIRA 
FORMA, E O SUFICIENTE PARA TER UM TRABALHO LIMPO E LIVRE DE ERROS. VEREMOS AS TRES FORMAS
NORMAIS, UMA A UMA, DETALHADAMENTE NAS PROXIMAS AULAS.*/

INSERT INTO CLIENTE VALUES( 'CARLA' ,'F' ,'C.LOPES@UOL.COM' ,45638854 , '9301-7585', 'RUA COPPER LEAF - WILLIAMSBURG - KITCHENER');

SELECT SEXO, COUNT (*) AS QTD FROM CLIENTE GROUP BY SEXO; /* ISSO SER UMA MA MODELAGEM QUE PODE TRAZER INFORMACOES ERRADAS */

/* PRIMEIRA FORMA NORMAL */

/*

1 - TODO CAMPO VEROTIZADO SE TORNARA UMA OUTRA TABELA
[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC] -> CARROS

2 - TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA.
QUANDO O CAMPO FOR DIVISIVEL

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O 
REGISTRO COMO SENDO UNICO. iSSO SER O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY

*/

