

CREATE DATABASE COMERCIO;

USE COMERCIO;

SELECT name FROM sys.databases; /* Esse ser o comando equivalente ao SHOW DATABASES no sql server */

SELECT * FROM CLIENTE;


/* Esse comando esta em myqsl, a baixo esta o comando adequado para sql server
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, /* ESSA COLUNA VAI SE AUTO INCREMENTAR. OU SEJA, EU NAO DEFINO UM NUMERO PRA ELA, QUEM CUIDA DISSO SER O BANCO */
	NOME VARCHAR(30) NOT NULL, /* NOT NULL SIGNIFICA QUE ELE NAO PODE SER UM CAMPO VAZIO, SE ESTIVER VAZIO ELE NAO VAI SER CRIADO */
	SEXO ENUM('M', 'F') NOT NULL,
	EMAI VARCHAR(50) UNIQUE, /* NESSE NEGOCIO NAO SER OBRIGATORIO FORNECER EMAIL, ENTRETANTO ESSE EMAIL DEVE SER UNICO, OU SEJA, O VALOR DO EMAIL NAO PODE SE REPETIR EM UMA COLUNA DE UM COM OUTRO, POR ISSO UTILIZEI O UNIQUE*/
	CPF VARCHAR(15) UNIQUE
);

*/

