/*

*/

USE COMERCIO;

CREATE TABLE CLIENTE ( /* Define as caterias dentro da tabela cliente */
    IDCLIENTE INT IDENTITY(1,1) PRIMARY KEY, 
    NOME VARCHAR(30) NOT NULL, 
    SEXO CHAR(1) NOT NULL CHECK (SEXO IN ('M', 'F')), 
    EMAIL VARCHAR(50) UNIQUE, 
    CPF VARCHAR(15) UNIQUE
);


/* Esse comando esta em myqsl, a baixo esta o comando adequado para sql server
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL
);
*/

CREATE TABLE ENDERECO(
	IDENDERECO INT IDENTITY(1,1) PRIMARY KEY,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL
);

/* Esse comando esta em myqsl, a baixo esta o comando adequado para sql server
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL

);
*/

CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY(1,1) PRIMARY KEY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN ('RES', 'COM', 'CEL')),
	NUMERO VARCHAR(30) NOT NULL
);


SELECT * FROM CLIENTE;

SELECT * FROM ENDERECO;

SELECT * FROM TELEFONE;

/* CRIEI AS TABELAS, NO PROXIMO TOPICO SERA NECESSARIO CRIAR AS CONEXOES DE RELACOES DE CADA TABELA PARA PODER FUNCIONAR DE FORMA CORRETA COM O DIAGRAMA */

/* ENDERECO - OBRIGATORIO
 CADASTRO DE SOMENTE UM.

 TELEFONE - NAO OBRIGATORIO
 CADASTRO DE MAIS DE UM (OPCIONAL)
*/