
USE COMERCIO;

/* CHAVE ESTRANGEIRA E A CHAVE PRIMARIA DE UMA TABELA QUE VAI ATE A OUTRA TABELA PARA FAZER REFERENCIA ENTRE REGISTROS */

/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA => ISSO VAI SER DEFINIDO PELA REGRA DE NEGOCIO */

/* EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA CARDINALIDADE N */