/* A CHAVE ESTRANGEIRA TAMBEM TEM A ANOTACAO AZUL ESCURO NOS DIAGRAMAS LOGICOS, OS DESENHOS, GERALMENTE O NOME DA CHAVE ESTRANGEIRA GERALMENTE TEM O MESMO NOME DA CHAVE PRIMARIA. NO CASO ISSO
SER BASICAMENTE UMA CONVENSAO => dica: Crtl + O ate arrumar os atributos no programa do diagrama.

RESSALTANDO QUE A REGRA DE NEGOCIO VAI SER DEFINIDA NA FORING KEY, ATRAVEZ DO COMANDO UNIQUE, 
PORQUE VAI DEFINIR E FECHAR UM RELACIONAMENTO 1 X 1*/

USE COMERCIO;

DROP TABLE CLIENTE;

CREATE TABLE CLIENTE ( /* Define as caterias dentro da tabela cliente */
    IDCLIENTE INT IDENTITY(1,1) PRIMARY KEY, 
    NOME VARCHAR(30) NOT NULL, 
    SEXO CHAR(1) NOT NULL CHECK (SEXO IN ('M', 'F')), 
    EMAIL VARCHAR(50) UNIQUE, 
    CPF VARCHAR(15) UNIQUE
);


CREATE TABLE ENDERECO(
	IDENDERECO INT IDENTITY(1,1) PRIMARY KEY,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY(1,1) PRIMARY KEY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN ('RES', 'COM', 'CEL')),
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT
);