/* MODELAGEM FISICA - SCRIPTS DE BANCO */

/* INICIANDO A MODELAGEM FISICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SELECT table_name 
FROM information_schema.tables 
WHERE table_type = 'BASE TABLE';

/* oU QUANDO ESTIVER EM DATABASE */

USE PROJETO;
SHOW TABLES;

/* DESCOBRINDO COMO SERA ESTRUTURA DE UMA TABELA */

DESC CLIENTE;