USE PROJETO;

DELETE FROM CLIENTE; /* Vai deletar todos os registros da tabela, por isso sempre usar o DELETE junto com o WHERE */

SELECT COUNT(*) FROM CLIENTE WHERE nome = 'ana';

DELETE FROM CLIENTE WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE;

INSERT INTO CLIENTE VALUES('CARLA', 'F', 'C.LOPES@UOL.COM', 45638854, '4575-0048', 'RUA COPPER LEAF - WILLIAMSBURG - KTCHENER' );

SELECT * FROM CLIENTE;

DELETE FROM CLIENTE WHERE NOME = 'CARLA' OR EMAIL = 'LILIAN@HTMAIL.COM' /* DELETA QUALQUER USUARIO QUE TEM AS INFORMACOES DE AMBAS DESSAS INFORMACOES */

SELECT * FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'LILIAN@HOTMAIL.COM' /* VAI DELETAR APENAS A CARLA QUE ENTRA NESSAS CARACTERISTICAS */